- name: To run multiple softwares
  hosts: test
  tasks:
  - name: Install package1
    package:
      name: "{{package1}}"
      state: present
  - name: Install package2
    package:
      name: "{{package2}}"
      state: present
  - name: Install package1
    package:
      name: "{{package3}}"
      state: present
