- hosts: myservers
  tasks:
  - package: 
      name: httpd 
      state: installed
  - copy: 
      src: index.html 
      dest: /var/www/html
  - service: 
      name: httpd 
      state: started 
      enabled: yes
